service: kontrolio-api

frameworkVersion: "2"

useDotenv: true

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  timeout: 10

package:
  individually: true

environment:
  ENV: production

functions:
  createUser:
    handler: dist/create_user
    events:
      - httpApi:
          path: /user
          method: post
    package:
      exclude:
        - ./**
      include:
        - ./dist/create_user
  createRecord:
    handler: dist/create_record
    events:
      - httpApi:
          path: /record
          method: post
    package:
      exclude:
        - ./**
      include:
        - ./dist/create_record
