service: kontrolio-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  timeout: 2
  memorySize: 128
  environment:
    ENV: production
    DB_USER: ${ssm:/kontrolio-db-user~true}
    DB_PASSWORD: ${ssm:/kontrolio-db-password~true}
    DB_NAME: ${ssm:/kontrolio-db-name~true}
    DB_HOST: ${ssm:/kontrolio-db-host~true}
    DB_PORT: ${ssm:/kontrolio-db-port~true}
    CLIENT_URL: https://kontrolio.com

package:
  individually: true

functions:
  createUser:
    handler: dist/create_user
    events:
      - httpApi:
          path: /user
          method: post
    package:
      exclude:
        - ./**
      include:
        - ./dist/create_user
  createRecord:
    handler: dist/create_record
    events:
      - httpApi:
          path: /record
          method: post
    package:
      exclude:
        - ./**
      include:
        - ./dist/create_record
