service: kontrolio-api

frameworkVersion: "2"

useDotenv: true

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  timeout: 20
  memorySize: 256
  stage: prod
  environment:
    ENV: ${self:custom.envVariables.ENV.${self:custom.currentStage}}
    DB_USER: ${self:custom.envVariables.DB_USER.${self:custom.currentStage}}
    DB_PASSWORD: ${self:custom.envVariables.DB_PASSWORD.${self:custom.currentStage}}
    DB_NAME: ${self:custom.envVariables.DB_NAME.${self:custom.currentStage}}
    DB_HOST: ${self:custom.envVariables.DB_HOST.${self:custom.currentStage}}
    DB_PORT: ${self:custom.envVariables.DB_PORT.${self:custom.currentStage}}
    SENDER_EMAIL: ${self:custom.envVariables.SENDER_EMAIL.${self:custom.currentStage}}
    JWT_SECRET: ${self:custom.envVariables.JWT_SECRET.${self:custom.currentStage}}
    ENABLE_EMAIL_AUTH: 0
    CLIENT_URL: https://kontrolio.com

package:
  individually: true

functions:
  migrations:
    handler: dist/migrations
    package:
      exclude:
        - ./**
      include:
        - ./dist/migrations

  createUser:
    handler: dist/create_user
    events:
      - httpApi:
          path: /user
          method: post
          authorizers:
            authorizer:
              audience:
                # https://github.com/dherault/serverless-offline/issues/1078#issuecomment-729681919
                - abcxxxxxxx
                - abcxxxxxxx
    package:
      exclude:
        - ./**
      include:
        - ./dist/create_user

  createRecord:
    handler: dist/create_record
    events:
      - httpApi:
          path: /record
          method: post
    package:
      exclude:
        - ./**
      include:
        - ./dist/create_record

  login:
    handler: dist/login
    events:
      - httpApi:
          path: /login
          method: post
          authorizers:
            authorizer:
              audience:
                # https://github.com/dherault/serverless-offline/issues/1078#issuecomment-729681919
                - abcxxxxxxx
                - abcxxxxxxx
    package:
      exclude:
        - ./**
      include:
        - ./dist/login

  get_api_key:
    handler: dist/get_api_key
    events:
      - httpApi:
          path: /api-key
          method: post
          authorizers:
            authorizer:
              audience:
                # https://github.com/dherault/serverless-offline/issues/1078#issuecomment-729681919
                - abcxxxxxxx
                - abcxxxxxxx
    package:
      exclude:
        - ./**
      include:
        - ./dist/get_api_key

  authorizer:
    handler: dist/authorizer

plugins:
  - serverless-offline
  - serverless-plugin-scripts

custom:
  currentStage: ${opt:stage, self:provider.sta"2021-01-19T18:11:35.682Z"ge}
  envVariables:
    ENV:
      prod: production
      dev: development
    DB_USER:
      prod: ${ssm:/kontrolio-db-user~true}
    DB_PASSWORD:
      prod: ${ssm:/kontrolio-db-password~true}
    DB_NAME:
      prod: ${ssm:/kontrolio-db-name~true}
    DB_HOST:
      prod: ${ssm:/kontrolio-db-host~true}
    DB_PORT:
      prod: ${ssm:/kontrolio-db-port~true}
    SENDER_EMAIL:
      prod: 0
    JWT_SECRET:
      prod: ${ssm:/kontrolio-jwt-secret~true}
  serverless-offline:
    ignoreJWTSignature: true
    httpPort: 9000
    useDocker: true
  scripts:
    hooks:
      "deploy:finalize": serverless invoke -f migrations
